name: Deploy

on:
  push:
    branches:
      - 'master'

jobs:
  deploy:
    name: Deploys the sdk
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup gpg
        uses: ./.github/actions/gpg-config
      - name: Deploy via gradle
        uses: ./.github/actions/gradle-deploy
